### ISSUE TITLE
`Spectrum` attribute names should be lowercase (and shorter)

### ISSUE THREAD

**Issue by maxmahlke** [bcarry/ska#7]
[PEP 8](https://peps.python.org/pep-0008/#method-names-and-instance-variables): Instance variables (attributes) should be lower-case, upper-case is reserved for classes.

https://github.com/bcarry/ska/blob/1257a666b56db4cfc9205dbe2931dce90327d53e/ska/spectrum.py#L17-L19

And I suggest to shorten them (or to at least accept shortened versions) for the sake of humanity.

```
self.Wavelength -> self.wavelength / self.wave
self.Reflectance -> self.reflectance / self.refl
self.Flux -> self.flux
```

**Comment by maxmahlke** [comment]
And since `self.Relfectance` is a flag rather than a data array, I suggest `self.is_refl` or `self.is_reflectance` instead.

**Comment by bcarry** [comment]
Good point. API modified in version 2.0 released today
